---

- hosts: all
  gather_facts: False
  remote_user: root  

  vars_files:
    - vars/main.yml
  
  roles:
    - name: user
      tags: user

    - name: ssh
      tags: ssh

  pre_tasks:
    - name: Update and install python
      raw: apt update && apt install -y python2.7 python-minimal
      become: true

    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: safe
        autoremove: yes
      become: true