---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yml

  roles:
    - name: essentials
      tags: essentials

    - name: timezone
      tags: timezone

    - name: fail2ban
      tags: fail2ban

    - name: misc
      tags: misc         

    - name: kamaln7.swapfile
      tags: swapfile
      become: true   

    - name: franklinkim.ufw
      tags: ufw
      become: true
